name: ox_test

services:
  # ----------- ox_pg_write --------------
  ox_pg_write:
    container_name: ox_pg_write
    image: ox_pg_write
    ports:
      - "8432:5432"
    build:
      context: ./ox_pg_write
      dockerfile: Dockerfile.dev
    env_file:
      - ./ox_pg_write/.env.docker
    volumes:
      - volume-ox_pg_write:/data/ox_pg_write
      # - ./ox_pg_write/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - webnet

  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
  #   image: localstack/localstack
  #   ports:
  #     - "127.0.0.1:4566:4566" # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559" # external services port range
  #   environment:
  #     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #     - DEBUG=${DEBUG:-0}
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"

  # ----------- ox_api_sys --------------
  ox_api_sys:
    container_name: ox_api_sys
    image: ox_api_sys
    build:
      context: ./ox_api_sys
      dockerfile: Dockerfile.dev
    ports:
      - "5050:5050"
    volumes:
      # - /tmp/ox_api_sys/npm-cache:/root/.npm:z
      - ./ox_api_sys:/app:z
      - /app/node_modules/
    depends_on:
      - ox_pg_write
    restart: always
    networks:
      - webnet

  # ----------- ox_api_api --------------
  ox_api_api:
    container_name: ox_api_api
    image: ox_api_api
    build:
      context: ./ox_api_api
      dockerfile: Dockerfile.dev
    ports:
      - "5051:5051"
    volumes:
      # - /tmp/ox_api_api/npm-cache:/root/.npm:z
      - ./ox_api_api:/app:z
      - /app/node_modules/
    depends_on:
      - ox_pg_write
    restart: always
    networks:
      - webnet

volumes:
  volume-ox_pg_write:
    driver: local
  pgadmin-data:
    driver: local

networks:
  webnet:
