name: Deploy_Multi_Environment

on:
  push:
    branches:
      - dev
      - stg
      - main
      # - do_nothing
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'stg'
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Determine Environment
        id: env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/stg" ]; then
            echo "environment=stg" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: determine-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "Deploying to ${{ needs.determine-environment.outputs.environment }} environment"
          # echo ">> ${{ env.MY_VAR }}"
          echo ${{ github }}
          # echo ">> ${{ vars[format('{0}_VAR', needs.determine-environment.outputs.environment)] }}"
          # echo "API_KEY=${{ secrets[format('{0}_API_KEY', needs.determine-environment.outputs.environment)] }}" >> $GITHUB_ENV

      - name: Deploy application
        run: echo "${{ needs.determine-environment.outputs.environment }}"

      # - name: Deploy application
      #   run: echo "Deploying application to ${{ needs.determine-environment.outputs.environment }} environment"
